#!/usr/bin/env bash

#
source_dir="/home/sergio/WebstormProjects/javalab-ang2/dist"
target_dir="/home/sergio/IdeaProjects/javalab/javalab/src/main/webapp"

cd $target_dir

rm -rf app
rm -rf assets
rm -rf node_modules
rm index.html
rm systemjs.config.js

cp -a $source_dir"/app" $target_dir
cp -a $source_dir"/assets" $target_dir
cp -a $source_dir"/node_modules" $target_dir
cp $source_dir"/index.html" $target_dir"/index.html"
cp $source_dir"/systemjs.config.js" $target_dir"/systemjs.config.js"
